/**:
  ros__parameters:
    vehicle:
      type: diagnostic_aggregator/AnalyzerGroup
      path: vehicle
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            # TODO(Tier IV): Consider splitting sensor input and control command output
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": vehicle_topic_status"]
              timeout: 1.0
        # added
        calibration:
          type: diagnostic_aggregator/AnalyzerGroup
          path: calibration
          analyzers:
            accel_brake_map_calibrator:
              type: diagnostic_aggregator/AnalyzerGroup
              path: accel_brake_map_calibrator
              analyzers:
                accel_brake_map_calibrator:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: accel_brake_map_calibrator
                  contains: [": accel_brake_map_calibrator"]
                  timeout: 1.0
        # calibration:
        #   type: diagnostic_aggregator/AnalyzerGroup
        #   path: calibration
        #   analyzers:
        #     accel_brake_map_calibrator:
        #       type: diagnostic_aggregator/GenericAnalyzer
        #       path: accel_brake_map_calibrator
        #       contains: [": accel_brake_map_calibrator"]
        #       timeout: 1.0
